"use client"
import { Provider } from 'react-redux';
import './globals.css';
import { Inter, Poppins } from 'next/font/google';
import store from '@/app/store/indexStore';

const inter = Poppins({ subsets: ['latin'], weight: '400' });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>{children}</Provider>
      </body>
    </html>
  );
}
